/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package classi.enumerativi;

public enum StatoTavolo {
    LIBERO,
    OCCUPATO,
    DA_PULIRE;
}