/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package classi.menu;

import java.util.List;

public class Componente {

	private String nome;
	private List<Piatto> listaPiatti;

	public Componente(String nome, List<Piatto> lista_piatti) {
		super();
		this.nome = nome;
		this.listaPiatti = lista_piatti;
	}

	public String getNome() {
		return nome;
	}

	public List<Piatto> getListaPiatti() {
		return listaPiatti;
	}

	public void aggiungiPiatto(Piatto piatto) {
		listaPiatti.add(piatto);
	}
}