/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package classi.menu;


public class Piatto {

	private String nome;
	private double prezzo;

	public Piatto(String nome, double prezzo) {
		super();
		this.nome = nome;
		this.prezzo = prezzo;
	}

	public String getNome() {
		return nome;
	}

	public double getPrezzo() {
		return prezzo;
	}

	private void setNome(String nome) {
		this.nome = nome;
	}

	private void setPrezzo(double prezzo) {
		this.prezzo = prezzo;
	}

	public boolean equals(Piatto p) {
		if(p == null) {
			return false;
		}
		return this.nome.equals(p.nome) && this.prezzo == p.prezzo;

	}
}