/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Classi;

import java.util.ArrayList;
import java.util.List;

public class Ordine {

	private List<PiattoOrdinato> lista_piatti_ordinati;
	private double prezzo_parziale;

	public Ordine() {
		lista_piatti_ordinati = new ArrayList<>();
		prezzo_parziale = 0;
	}
	

	public double getPrezzo_parziale() {
		aggiorna_prezzo_parziale();
		return prezzo_parziale;
	}

	private void aggiorna_prezzo_parziale() {
		double prezzo = 0;
		for (PiattoOrdinato piatto_ordinato : lista_piatti_ordinati) {
			prezzo += prezzo + piatto_ordinato.getPrezzo() * piatto_ordinato.getQuantita();
		}
		prezzo_parziale = prezzo;
	}
}