/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Classi;

import java.util.List;

public class Ordine {

	private int precedenza;
	private List<PiattoOrdinato> lista_piatti_ordinati;

	private double prezzo_parziale;

	private int getPrecedenza() {
		return precedenza;
	}

	private double getPrezzo_parziale() {
		return prezzo_parziale;
	}

	public void setPrecedenza(int precedenza) {
		this.precedenza = precedenza;
	}

	private void setPrezzo_parziale(double prezzo_parziale) {
		this.prezzo_parziale = prezzo_parziale;
	}
}