/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Classi;

public class PiattoOrdinato {

	private Piatto piatto;
	private int quantita;
	private double prezzo;
	private String commento;

	public PiattoOrdinato(int quantita , String commento , Piatto piatto) {
		super();
		this.quantita  = quantita ;
		this.commento = commento;
		this.piatto = piatto;
	}

	public int getQuantita () {
		return quantita ;
	}

	public double getPrezzo() {
		aggiornaPrezzo();
		return prezzo;
	}

	private void aggiornaPrezzo() {
		prezzo = piatto.getPrezzo() * quantita ;
	}

	public String getCommento() {
		return commento;
	}

	public void setQuantita (int quantita ) {
		this.quantita = quantita ;
	}
	
	public void setCommento(String commento) {
		this.commento = commento;
	}

}