/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Classi;

public class PiattoOrdinato {

	private Piatto piatto;
	private int quantità;
	private double prezzo;
	private String commento;

	public PiattoOrdinato(int quantità, String commento , Piatto piatto) {
		super();
		this.quantità = quantità;
		this.commento = commento;
		this.piatto = piatto;
	}

	public int getQuantità() {
		return quantità;
	}

	public double getPrezzo() {
		aggiornaPrezzo();
		return prezzo;
	}

	private void aggiornaPrezzo() {
		prezzo = piatto.getPrezzo() * quantità;
	}

	public String getCommento() {
		return commento;
	}

	public void setQuantità(int quantità) {
		this.quantità = quantità;
	}
	
	public void setCommento(String commento) {
		this.commento = commento;
	}

}