/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Classi;

import Classi.Enum.Stato_Tavolo;

public class Tavolo {

	private int nome;
	private int num_posti_massimi;
	private Stato_Tavolo stato;
	private ResocontoTavolo resoconto_tavolo;

	public Tavolo(int nome, int num_post_massimi) {
		super();
		this.nome = nome;
		this.num_posti_massimi = num_post_massimi;
		stato = Stato_Tavolo.LIBERO;
	}

	public int getNome() {
		return nome;
	}

	public int getNum_posti_massimi() {
		return num_posti_massimi;
	}

	public Stato_Tavolo getStato() {
		return stato;
	}

	private void setNum_posti_massimi(int num_post_massimi) {
		this.num_posti_massimi = num_post_massimi;
	}

	public void setStato(Stato_Tavolo stato) {
		this.stato = stato;
	}

	/**
	 * @param num numero di posti
	 */

	public void modifica_posti(int num) {
		num_posti_massimi = num;
	}
	
	/**
	 * @param nome
	 */

	public void modifica_nome(int nome) {
		this.nome = nome;
	}
}