/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package classi.tavolo;

import java.util.ArrayList;
import java.util.List;

import classi.ordine.Ordine;

public class ResocontoTavolo {
    
	public static final double COSTO_COPERTO  = 2;
	
	private int numCoperti;
    private double prezzoTotale;
    private List<Ordine> listaOrdini;
    private int numeroOrdini;
    
    public ResocontoTavolo(int num_coperti) {
		super();
		this.numCoperti = num_coperti;
		listaOrdini = new ArrayList<Ordine>();
		numeroOrdini = 0;
	}

	public int getNumCoperti() {
        return numCoperti;
    }

    public double getPrezzoTotale() {
        aggiornaPrezzoTotale();
        return prezzoTotale;
    }

    private void aggiornaPrezzoTotale() {
    	double prezzo = numCoperti * COSTO_COPERTO;
    	for (Ordine ordine : listaOrdini) {
			prezzo += ordine.getPrezzo_parziale();
		}
    	prezzoTotale = prezzo;
	}

	private void setPrezzoTotale(double prezzo_totale) {
        this.prezzoTotale = prezzo_totale;
    }

    public void aggingiOrdine(Ordine ordine) {
		listaOrdini.add(ordine);
	}
    public List<Ordine> getListaOrdini() {
		return listaOrdini;
	}
}