/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package classi.tavolo;

import classi.enumerativi.StatoTavolo;

public class Tavolo {

	private int nome;
	private int num_posti_massimi;
	private StatoTavolo stato;
	public ResocontoTavolo resocontoTavolo;

	public Tavolo(int nome, int num_post_massimi) {
		super();
		this.nome = nome;
		this.num_posti_massimi = num_post_massimi;
		stato = StatoTavolo.LIBERO;
		
	}

	public int getNome() {
		return nome;
	}

	public int getNumPostiMassimi() {
		return num_posti_massimi;
	}

	public StatoTavolo getStato() {
		return stato;
	}

	public void setNumPostiMassimi(int num_post_massimi) {
		this.num_posti_massimi = num_post_massimi;
	}

	public void setStato(StatoTavolo stato) {
		this.stato = stato;
	}

	/**
	 * @param num numero di posti
	 */

	public void modificaPosti(int num) {
		num_posti_massimi = num;
	}
	
	/**
	 * @param nome
	 */

	public void modificaNome(int nome) {
		this.nome = nome;
	}

	public void pagato() {
		setStato(StatoTavolo.DA_PULIRE);
		resocontoTavolo = null;
	}
	
	@Override
	public String toString() {
		return "Tavolo n° " + nome + ", numero posti: " + num_posti_massimi;
	}
}