/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLoAhWYZZbS1I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLoAhWYZZbS1I= >>
// ----------- >>
public class Ordini {
    // ----------- << attribute.annotations@AAAAAAGLoAh5O5bj3Ew= >>
    // ----------- >>
    private void precedenza;

    // ----------- << attribute.annotations@AAAAAAGLoBOhYboDNxI= >>
    // ----------- >>
    private double prezzo_parziale;

    private void getPrecedenza() {
        return precedenza;
    }

    private double getPrezzo_parziale() {
        return prezzo_parziale;
    }

    private void setPrecedenza(void precedenza) {
        this.precedenza = precedenza;
    }

    private void setPrezzo_parziale(double prezzo_parziale) {
        this.prezzo_parziale = prezzo_parziale;
    }

// ----------- << class.extras@AAAAAAGLoAhWYZZbS1I= >>
// ----------- >>
}