/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLoARBmZUn47U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLoARBmZUn47U= >>
// ----------- >>
public class PiattiOrdinati {
    // ----------- << attribute.annotations@AAAAAAGLoARnQZVROZU= >>
    // ----------- >>
    private int quantità;

    // ----------- << attribute.annotations@AAAAAAGLoAVkTJVYNwM= >>
    // ----------- >>
    private double prezzo;

    // ----------- << attribute.annotations@AAAAAAGLoAf2TpWeGy0= >>
    // ----------- >>
    private Strign commento;

    private int getQuantità() {
        return quantità;
    }

    private double getPrezzo() {
        return prezzo;
    }

    private Strign getCommento() {
        return commento;
    }

    private void setQuantità(int quantità) {
        this.quantità = quantità;
    }

    private void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

    private void setCommento(Strign commento) {
        this.commento = commento;
    }

// ----------- << class.extras@AAAAAAGLoARBmZUn47U= >>
// ----------- >>
}