/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLoAY9nZVmPk0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLoAY9nZVmPk0= >>
// ----------- >>
public class Piatto {
    // ----------- << attribute.annotations@AAAAAAGLoAeHKpWQTDw= >>
    // ----------- >>
    private Strign nome;

    // ----------- << attribute.annotations@AAAAAAGLoAegCJWXU3E= >>
    // ----------- >>
    private double prezzo;

    private Strign getNome() {
        return nome;
    }

    private double getPrezzo() {
        return prezzo;
    }

    private void setNome(Strign nome) {
        this.nome = nome;
    }

    private void setPrezzo(double prezzo) {
        this.prezzo = prezzo;
    }

// ----------- << class.extras@AAAAAAGLoAY9nZVmPk0= >>
// ----------- >>
}