/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLoAEh2JTmK1M= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLoAEh2JTmK1M= >>
// ----------- >>
public class ResocontoTavolo {
    // ----------- << attribute.annotations@AAAAAAGLoAFoIJUQ+i4= >>
    // ----------- >>
    private int num_coperti;

    // ----------- << attribute.annotations@AAAAAAGLoAKkvJUfJ2g= >>
    // ----------- >>
    private double prezzo_totale;

    private int getNum_coperti() {
        return num_coperti;
    }

    private double getPrezzo_totale() {
        return prezzo_totale;
    }

    private void setNum_coperti(int num_coperti) {
        this.num_coperti = num_coperti;
    }

    private void setPrezzo_totale(double prezzo_totale) {
        this.prezzo_totale = prezzo_totale;
    }

// ----------- << class.extras@AAAAAAGLoAEh2JTmK1M= >>
// ----------- >>
}