/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLoBA17K1BvDk= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLoBA17K1BvDk= >>
// ----------- >>
public enum Stato_Tavolo {
    Libero,
    Occupato,
    Da_Pulire;

// ----------- << enum.extras@AAAAAAGLoBA17K1BvDk= >>
// ----------- >>
}