/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGLn/9g65ShjFg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGLn/9g65ShjFg= >>
// ----------- >>
public class Tavolo {
    // ----------- << attribute.annotations@AAAAAAGLn/+P8JTNi8A= >>
    // ----------- >>
    private int nome;

    // ----------- << attribute.annotations@AAAAAAGLn//PkZTUM4o= >>
    // ----------- >>
    private int num_post_massimi;

    // ----------- << attribute.annotations@AAAAAAGLoAAxupTbGQI= >>
    // ----------- >>
    private void nume;

    // ----------- << attribute.annotations@AAAAAAGLoA+x5qwIw5E= >>
    // ----------- >>
    private Stato_Tavolo stato;

    private int getNome() {
        return nome;
    }

    private int getNum_post_massimi() {
        return num_post_massimi;
    }

    private void getNume() {
        return nume;
    }

    private Stato_Tavolo getStato() {
        return stato;
    }

    private void setNome(int nome) {
        this.nome = nome;
    }

    private void setNum_post_massimi(int num_post_massimi) {
        this.num_post_massimi = num_post_massimi;
    }

    private void setNume(void nume) {
        this.nume = nume;
    }

    private void setStato(Stato_Tavolo stato) {
        this.stato = stato;
    }

    /**
    * @param num
    */

    // ----------- << method.annotations@AAAAAAGLoBdqhcaumL4= >>
    // ----------- >>
    public void modifica_posti(int num) {
    // ----------- << method.body@AAAAAAGLoBdqhcaumL4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGLoBgTFsdEhCE= >>
    // ----------- >>
    public static void Operation2() {
    // ----------- << method.body@AAAAAAGLoBgTFsdEhCE= >>
    // ----------- >>
    }
    /**
    * @param num
    */

    // ----------- << method.annotations@AAAAAAGLoBoonMpp3VE= >>
    // ----------- >>
    public void modifica_nome(int num) {
    // ----------- << method.body@AAAAAAGLoBoonMpp3VE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGLoBq+GMxIHuI= >>
    // ----------- >>
    public void Operation1() {
    // ----------- << method.body@AAAAAAGLoBq+GMxIHuI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGLn/9g65ShjFg= >>
// ----------- >>
}